# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_pickle', picklefield.fields.PickledObjectField(editable=False)),
                ('models_pickle', picklefield.fields.PickledObjectField(editable=False)),
                ('run_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PatentClaim',
            fields=[
                ('patentid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('claim', models.TextField()),
            ],
        ),
    ]
