# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('patentid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('claim', models.TextField()),
                ('run_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='PatentClaim',
        ),
        migrations.RemoveField(
            model_name='lsimodel',
            name='index_pickle',
        ),
    ]
