# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_home', '0002_auto_20170818_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent_Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_id', models.CharField(max_length=200)),
                ('claim', models.TextField()),
                ('run_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
