# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_home', '0004_auto_20170819_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentclaimtext',
            name='patent_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
