# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent_home', '0006_auto_20170819_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patentclaim',
            old_name='patent_id',
            new_name='patent_Num',
        ),
    ]
