# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_home', '0007_auto_20170819_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentclaim',
            name='patent_Num',
            field=models.TextField(null=True),
        ),
    ]
