# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent_home', '0009_auto_20170819_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patentclaimtext',
            old_name='Eventid',
            new_name='Event_id',
        ),
    ]
