# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent_home', '0010_auto_20170819_0447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatentClaimText',
            new_name='ClaimText',
        ),
    ]
