# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patent_home', '0011_auto_20170819_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimtext',
            name='id',
        ),
        migrations.AlterField(
            model_name='claimtext',
            name='Event_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
